
const DATA_URLS=['data/indas-data.json','../data/indas-data.json'], VERSION='4.0.0', COMPRESSED_DATA_SETS=[['data/indas-data.json.gz.b64.part1','data/indas-data.json.gz.b64.part2','data/indas-data.json.gz.b64.part3'],['../data/indas-data.json.gz.b64.part1','../data/indas-data.json.gz.b64.part2','../data/indas-data.json.gz.b64.part3']], KEY='mcaIndAsXbrlWorkbenchV4';
let DATA=null;
const state={page:'home',elr:0,ruleQuery:'',showOnlyPopulated:false,profile:{cin:'',companyName:'',fyStart:'',fyEnd:'',incorporationDate:'',currency:'INR',nature:'Standalone',firstYear:false,rounding:'Actuals',cashFlow:'',pan:'',address:'',industry:''},facts:{},dimRows:{},contexts:[],footnotes:[],issues:[],dirty:false};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const q=(prefix,name)=>`${prefix}:${name}`, E=()=>DATA.elements, el=q=>DATA._emap[q]||null;
const nonblank=v=>v!==undefined&&v!==null&&String(v).trim()!=='';
const toast=m=>{const x=$('#toast');x.textContent=m;x.classList.add('show');clearTimeout(window.__tt);window.__tt=setTimeout(()=>x.classList.remove('show'),2500)};
const save=()=>{localStorage.setItem(KEY,JSON.stringify({profile:state.profile,facts:state.facts,dimRows:state.dimRows,contexts:state.contexts,footnotes:state.footnotes}));state.dirty=false;$('#saveState').textContent='Saved';toast('Project saved locally.')};
const dirty=()=>{state.dirty=true;$('#saveState').textContent='Changed'};
function roleName(r){return DATA.roles[r]||r}
function currentDates(){return {start:state.profile.fyStart,end:state.profile.fyEnd}}
function priorDates(){if(!state.profile.fyStart||!state.profile.fyEnd)return {start:'',end:''};const a=new Date(state.profile.fyStart+'T00:00:00'),b=new Date(state.profile.fyEnd+'T00:00:00');a.setFullYear(a.getFullYear()-1);b.setFullYear(b.getFullYear()-1);return {start:a.toISOString().slice(0,10),end:b.toISOString().slice(0,10)}}
function typeKind(e){const t=String(e?.type||'');if(t.includes('monetaryItemType'))return'monetary';if(t.includes('sharesItemType'))return'shares';if(t.includes('perShareItemType'))return'perShare';if(t.includes('percentItemType')||t.includes('decimalItemType'))return'pure';if(t.includes('dateItemType'))return'date';if(t.includes('booleanItemType'))return'boolean';if(t.includes('integerItemType')||t.includes('nonNegativeIntegerItemType')||t.includes('positiveIntegerItemType'))return'integer';if(t.includes('escapedItemType'))return'html';return'text'}
function inputFor(concept,period,role){const e=el(concept);if(!e)return'';const key=`${concept}|${period}`;const val=state.facts[key]??'';const kind=typeKind(e);if(kind==='boolean')return `<select class="fact-input" data-fact="${esc(concept)}" data-period="${period}"><option value=""></option><option ${val==='true'?'selected':''} value="true">Yes</option><option ${val==='false'?'selected':''} value="false">No</option></select>`;
if(kind==='html')return `<textarea class="fact-input" data-fact="${esc(concept)}" data-period="${period}" placeholder="MCA-compliant XHTML text">${esc(val)}</textarea>`;
let typ=kind==='date'?'date':(kind==='integer'||kind==='monetary'||kind==='perShare'||kind==='pure'||kind==='shares')?'number':'text';let step=kind==='integer'||kind==='shares'?'1':'0.01';
return `<input class="fact-input" ${typ==='number'?'type="number" step="'+step+'"':'type="'+typ+'"'} data-fact="${esc(concept)}" data-period="${period}" value="${esc(val)}" placeholder="${kind}">`}
function setFactInputs(){ $$('.fact-input').forEach(x=>x.onchange=()=>{state.facts[`${x.dataset.fact}|${x.dataset.period}`]=x.value;dirty()})}
function nav(){const items=[['home','Control centre'],['general','General information'],['sections','Financial statements & notes'],['dimensions','Dimensional disclosures'],['contexts','Contexts & units'],['rules','Rules & preflight'],['calc','Calculations'],['xml','XML preview']];$('#nav').innerHTML=items.map(x=>`<button class="nav ${state.page===x[0]?'active':''}" data-page="${x[0]}">${x[1]}</button>`).join('');$$('[data-page]').forEach(b=>b.onclick=()=>{state.page=b.dataset.page;render()})}
function header(){const names={home:['Control centre','Set up the filing and monitor readiness.'],general:['General information','MCA IND-AS general-information facts and filing controls.'],sections:[roleName(DATA.elrs[state.elr]?.role||''),'Enter current and prior facts using the taxonomy presentation structure.'],dimensions:['Dimensional disclosures','Taxonomy-defined axes, members and typed dimensions.'],contexts:['Contexts & units','Review the contexts the generator will construct and manage footnotes.'],rules:['Rules & preflight','MCA business rules, taxonomy checks and correction guidance.'],calc:['Calculation & continuity','Inspect calculation relationships and opening/closing consistency before XML generation.'],xml:['XML preview','Inspect the generated instance before saving it.']};const h=names[state.page]||names.home;$('#title').textContent=h[0];$('#desc').textContent=h[1];$('#meta').innerHTML=`<span>${esc(DATA.meta.taxonomyVersion)}</span><span>${esc(DATA.meta.businessRulesVersion)}</span><span>${state.profile.nature}</span>`}
function tabs(){if(state.page!=='sections'){$('#tabs').innerHTML='';return}$('#tabs').innerHTML=DATA.elrs.map((x,i)=>`<button class="tab ${i===state.elr?'active':''}" data-elr="${i}">${esc(x.name.replace(/^\[[^\]]+\]\s*/,''))}</button>`).join('');$$('[data-elr]').forEach(b=>b.onclick=()=>{state.elr=+b.dataset.elr;render()})}
function home(){const filled=Object.values(state.facts).filter(nonblank).length+Object.values(state.dimRows).flat().length;return `<div class="grid three"><div class="card"><h3>Filing profile</h3><p class="hint">The profile controls contexts, reporting-period restrictions and XML metadata.</p><button class="smallbtn primary" data-go="general">Open general information</button><button class="smallbtn" data-go="calc" style="margin-left:6px">Check calculations</button></div><div class="card"><h3>Taxonomy coverage</h3><p><b>${DATA.meta.elementCount}</b> concepts • <b>${DATA.meta.elrCount}</b> presentation ELRs • <b>${DATA.meta.definitionArcCount}</b> dimensional arcs</p><p class="hint">All taxonomy data is parsed from the supplied MCA package.</p></div><div class="card"><h3>Preparation status</h3><p><b>${filled}</b> populated data entries</p><p><b>${state.issues.filter(x=>x.level==='error').length}</b> errors • <b>${state.issues.filter(x=>x.level==='warning').length}</b> warnings</p><button class="smallbtn" data-go="rules">Run business-rule preflight</button></div></div>
<div class="card" style="margin-top:14px"><h2>Recommended workflow</h2><div class="grid three"><div><b>1. Profile</b><p class="hint">Enter CIN, company, FY, standalone/consolidated, incorporation date and rounding.</p></div><div><b>2. Tag</b><p class="hint">Use presentation ELRs for ordinary facts and the dedicated dimensional editor for tables.</p></div><div><b>3. Preflight → XML</b><p class="hint">Resolve technical, mandatory, dimensional, calculation and period checks before generating XML.</p></div></div></div>
<div class="card" style="margin-top:14px"><h2>Important MCA constraints</h2><ul><li>No taxonomy extensions are supported.</li><li>Current and previous financial year information are expected where applicable.</li><li>Monetary reporting currency is INR except specified subsidiary-information exemptions.</li><li>Default members must not be rendered in the instance; dimensional contexts must match taxonomy base sets.</li><li>The final authority remains the MCA XBRL Validation Tool and pre-scrutiny workflow.</li></ul></div>`}
function general(){const p=state.profile;return `<div class="grid two"><div class="card"><h2>Filing profile</h2><div class="grid two">
${field('CIN','cin',p.cin,'text','Required; used as context identifier.')} ${field('Company name','companyName',p.companyName,'text','Written to NameOfCompany.')}
${field('FY start','fyStart',p.fyStart,'date','Current reporting period start.')} ${field('FY end','fyEnd',p.fyEnd,'date','Current reporting period end.')}
${field('Date of incorporation','incorporationDate',p.incorporationDate,'date','Used by date business rule.')} ${field('PAN','pan',p.pan,'text','Optional general-information value.')}
<div class="field"><label>Nature of report</label><select data-profile="nature"><option ${p.nature==='Standalone'?'selected':''}>Standalone</option><option ${p.nature==='Consolidated'?'selected':''}>Consolidated</option></select></div>
<div class="field"><label>Reporting currency</label><select data-profile="currency"><option value="INR" selected>INR</option></select></div>
${field('Rounding used in financial statements','rounding',p.rounding,'text','Example: Actuals, thousands, lakhs, crores. Numeric XML facts themselves never carry a scale factor.')}
${field('Cash-flow statement','cashFlow',p.cashFlow,'text','Example: Direct / Indirect.')}
${field('Industry','industry',p.industry,'text','Optional.')}<div class="field wide"><label>Registered office address</label><textarea data-profile="address">${esc(p.address)}</textarea></div>
<div class="field wide"><label>First financial year of company</label><select data-profile="firstYear"><option value="false" ${!p.firstYear?'selected':''}>No</option><option value="true" ${p.firstYear?'selected':''}>Yes</option></select></div>
</div></div>
<div class="card"><h2>Taxonomy-mapped general information</h2><p class="hint">These concepts are shown separately so the filing profile remains easy to use. Values are stored as normal XBRL facts.</p>${generalConcepts().map(c=>`<div class="field" style="margin:10px 0"><label>${esc(el(c)?.label||c)} <span class="code">${esc(c)}</span></label>${inputFor(c,'current','general')}</div>`).join('')}</div></div>`}
function field(label,key,val,type='text',hint=''){return `<div class="field"><label>${esc(label)}</label><input data-profile="${key}" type="${type}" value="${esc(val)}"><span class="hint">${esc(hint)}</span></div>`}
function generalConcepts(){return ['in-ca:NameOfCompany','in-ca:CorporateIdentityNumber','in-ca:PermanentAccountNumberOfEntity','in-ca:AddressOfRegisteredOfficeOfCompany','in-ca:PeriodCoveredByFinancialStatements','in-ca:DateOfStartOfReportingPeriod','in-ca:DateOfEndOfReportingPeriod','in-ca:NatureOfReportStandaloneConsolidated','in-ca:DescriptionOfPresentationCurrency','in-ca:LevelOfRoundingUsedInFinancialStatements','in-ca:TypeOfCashFlowStatement'].filter(c=>el(c))}
function rolePresentation(role){return DATA.presentation.filter(x=>x.role===role).sort((a,b)=>(+a.order||0)-(+b.order||0))}
function sections(){const r=DATA.elrs[state.elr];if(!r)return '';const ps=rolePresentation(r.role);const uniq=[];const seen=new Set();for(const x of ps){if(seen.has(x.q)||x.abstract==='true')continue;if(x.name.endsWith('Axis')||x.name.endsWith('Member')||x.name.endsWith('Table')||x.name.endsWith('LineItems'))continue;seen.add(x.q);uniq.push(x)}const dim=r.dimensional?`<div class="card" style="margin-bottom:14px"><div class="toolbar"><div class="grow"><h2>Dimensional table</h2><div class="hint">This ELR contains ${r.axes.length} taxonomy-defined axis/axes. Use the dedicated editor to create member-qualified facts.</div></div><button class="smallbtn primary" data-dimrole="${esc(r.role)}">Open dimensional editor</button></div>${r.axes.map(a=>`<span class="status">${esc(a.label)}${a.typed?' • typed':''}</span> `).join('')}</div>`:'';return `${dim}<div class="card"><div class="toolbar"><div class="grow"><h2>Non-dimensional / primary facts</h2><div class="hint">Presentation order comes directly from the taxonomy. Abstracts and table scaffolding are suppressed.</div></div><div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap"><input class="search" id="conceptSearch" style="max-width:320px" placeholder="Search concept or label…"><label class="hint" style="display:flex;align-items:center;gap:6px"><input id="populatedOnly" type="checkbox" ${state.showOnlyPopulated?'checked':''}> populated only</label></div></div><div class="table-wrap"><table class="table"><thead><tr><th>Concept</th><th>Current</th><th>Previous</th><th>Type</th></tr></thead><tbody id="factBody">${uniq.map(x=>factRow(x)).join('')}</tbody></table></div></div>`}
function factRow(x){const e=el(x.q);const req=isMandatoryConcept(x.q);return `<tr data-search="${esc((x.label+' '+x.q).toLowerCase())}"><td><b>${esc(x.label)}</b>${req?'<span class="req"> REQUIRED</span>':''}<div class="code">${esc(x.q)}</div></td><td>${inputFor(x.q,'current',state.elr)}</td><td>${inputFor(x.q,'prior',state.elr)}</td><td><span class="status">${typeKind(e)}</span>${e?.balance?` <span class="code">${e.balance}</span>`:''}</td></tr>`}
function isMandatoryConcept(qn){return DATA.specificRules.some(r=>r.q===qn&&/mandatory/i.test(r.rule))||false}
function dimensions(){const roles=DATA.elrs.filter(x=>x.dimensional);return `<div class="card"><h2>Dimensional disclosures</h2><p class="hint">Choose an ELR/table, then add one row per member combination and line item. Explicit members are restricted to taxonomy relationships; typed members accept a user-supplied value.</p><div class="grid three">${roles.map((r,i)=>`<div class="card"><b>${esc(r.name)}</b><div class="hint" style="margin:6px 0">${r.axes.length} axis • ${r.lineItems.length} line items</div><button class="smallbtn primary" data-dimrole="${esc(r.role)}">Open</button></div>`).join('')}</div></div>`}
function dimEditor(role){const r=DATA.elrs.find(x=>x.role===role);if(!r)return'';const rows=state.dimRows[role]||[];const lineItems=r.lineItems||[];const mandatory=mandatoryForRole(r);return `<div class="card"><div class="toolbar"><div class="grow"><h2>${esc(r.name)}</h2><div class="hint">Add rows. Each row is one dimensional fact. Required line items are flagged by the supplied MCA business rules.</div></div><button class="smallbtn" data-dimback>Back</button><button class="smallbtn primary" data-addrow="${esc(role)}">Add fact row</button></div><div class="table-wrap"><table class="table" style="min-width:1250px"><thead><tr><th>Line item</th>${r.axes.map(a=>`<th>${esc(a.label)}<div class="hint">${a.typed?'Typed member':'Explicit member'}</div></th>`).join('')}<th>Current</th><th>Previous</th><th></th></tr></thead><tbody>${rows.map((row,i)=>dimRow(r,row,i,mandatory)).join('')}</tbody></table></div><p class="hint">Tip: create separate rows for each line item/member combination. This keeps large IND-AS tables manageable on normal screens.</p></div>`}
function mandatoryForRole(r){const name=r.name.replace(/^\[[^\]]+\]\s*/,'');const raw=DATA.mandatoryLineItems.find(x=>x.table&&name.includes(x.table.replace(/Table$/i,'')))?.requirements||'';const names=[];for(const e of DATA.elements){if(raw.includes(e.name))names.push(e.q)}return names}
function dimRow(r,row,i,mandatory){return `<tr><td><select class="dim-cell" data-dr="${esc(r.role)}" data-i="${i}" data-k="line"><option value="">Select line item…</option>${r.lineItems.map(x=>`<option value="${esc(x.q)}" ${row.line===x.q?'selected':''}>${esc(x.label)}</option>`).join('')}</select><div class="code">${esc(row.line||'')}</div>${mandatory.includes(row.line)?'<span class="req">MANDATORY</span>':''}</td>${r.axes.map((a,j)=>`<td>${a.typed?`<input class="dim-cell" data-dr="${esc(r.role)}" data-i="${i}" data-axis="${esc(a.q)}" value="${esc((row.dims||{})[a.q]||'')}" placeholder="Typed member">`:`<select class="dim-cell" data-dr="${esc(r.role)}" data-i="${i}" data-axis="${esc(a.q)}"><option value="">Select…</option>${a.members.filter(m=>!isDefaultMember(a.q,m.q)).map(m=>`<option value="${esc(m.q)}" ${((row.dims||{})[a.q]===m.q)?'selected':''}>${esc(m.label)}</option>`).join('')}</select>`}<div class="code">${esc((row.dims||{})[a.q]||'')}</div></td>`).join('')}<td>${dimInput(row,'current')}</td><td>${dimInput(row,'prior')}</td><td><button class="smallbtn" data-delrow="${esc(r.role)}" data-i="${i}">Delete</button></td></tr>`}
function dimInput(row,p){const e=el(row.line);const v=row[p]??'';const typ=typeKind(e);if(typ==='boolean')return`<select data-dr="${esc(row._role||'')}" data-i="${row._i}" data-period="${p}" class="dimval"><option value=""></option><option ${v==='true'?'selected':''} value="true">Yes</option><option ${v==='false'?'selected':''} value="false">No</option></select>`;return`<input class="dimval" data-dr="${esc(row._role||'')}" data-i="${row._i}" data-period="${p}" value="${esc(v)}" placeholder="${typ}">`}
function isDefaultMember(axis,member){return DATA.definitions.some(d=>d.arcrole.endsWith('dimension-default')&&d.from===axis&&d.to===member)}
function contexts(){const cs=buildContexts(false);return `<div class="grid two"><div class="card"><h2>Generated contexts</h2><p class="hint">Contexts are deterministic and created only for facts actually reported. Base contexts are shown first.</p><div class="table-wrap"><table class="table"><thead><tr><th>ID</th><th>Period</th><th>Dimensions</th></tr></thead><tbody>${cs.map(c=>`<tr><td class="code">${c.id}</td><td>${c.instant||c.start+' → '+c.end}</td><td>${c.dims.length?c.dims.map(d=>esc(d.axis+' = '+d.member)).join('<br>'):'Base context'}</td></tr>`).join('')||'<tr><td colspan=3 class="empty">No contexts yet.</td></tr>'}</tbody></table></div></div><div class="card"><h2>Units & footnotes</h2><p class="hint">Units are inferred from taxonomy data. Only units used by facts will be emitted.</p><div>${unitSummary().map(u=>`<div class="issue">${esc(u)}</div>`).join('')}</div><h3 style="margin-top:15px">Footnotes</h3><button class="smallbtn" data-addfoot>Add footnote</button>${state.footnotes.map((f,i)=>`<div class="issue"><select data-foot="${i}" data-k="fact"><option value="">Select fact…</option>${factKeys().map(k=>`<option value="${esc(k)}" ${f.fact===k?'selected':''}>${esc(k)}</option>`).join('')}</select><textarea data-foot="${i}" data-k="text" placeholder="MCA-compliant footnote HTML">${esc(f.text||'')}</textarea></div>`).join('')}</div></div>`}
function factKeys(){return Object.keys(state.facts).filter(k=>nonblank(state.facts[k]))}
function unitFor(e){const k=typeKind(e);if(k==='monetary')return'INR';if(k==='shares')return'shares';if(k==='perShare')return'INRPerShare';if(k==='pure')return'pure';return null}
function unitSummary(){const s=new Set();for(const [k,v] of Object.entries(state.facts)){if(nonblank(v)){const e=el(k.split('|')[0]);const u=unitFor(e);if(u)s.add(u)}}for(const rows of Object.values(state.dimRows))for(const r of rows){if(nonblank(r.current)||nonblank(r.prior)){const u=unitFor(el(r.line));if(u)s.add(u)}}return [...s].map(x=>x==='INR'?'iso4217:INR':x==='shares'?'xbrli:shares':x==='INRPerShare'?'divide(iso4217:INR / xbrli:shares)':'xbrli:pure')}
function buildContexts(includeXml=true){const out=[];const add=(period,dims)=>{const p=period==='current'?currentDates():priorDates();const sig=JSON.stringify([period,p,dims]);let c=out.find(x=>x.sig===sig);if(!c){c={id:(period==='current'?'C':'P')+(out.filter(x=>x.period===period).length+1),period,start:p.start,end:p.end,instant:'',dims,sig}};if(!out.includes(c))out.push(c);return c};add('current',[]);add('prior',[]);
for(const [k,v] of Object.entries(state.facts))if(nonblank(v)){const [concept,period]=k.split('|');const e=el(concept);if(e?.periodType==='instant'){const p=period==='current'?currentDates():priorDates();add(period,[]).instant=p.end}else add(period,[])}
for(const [role,rows] of Object.entries(state.dimRows))for(const row of rows){if(!nonblank(row.line))continue;for(const p of ['current','prior'])if(nonblank(row[p]))add(p,Object.entries(row.dims||{}).filter(x=>nonblank(x[1])).map(([axis,member])=>({axis,member})))}
return out}
function unitXML(e){const u=unitFor(e);if(u==='INR')return'<xbrli:unit id="INR"><xbrli:measure>iso4217:INR</xbrli:measure></xbrli:unit>';if(u==='shares')return'<xbrli:unit id="shares"><xbrli:measure>xbrli:shares</xbrli:measure></xbrli:unit>';if(u==='perShare')return'<xbrli:unit id="INRPerShare"><xbrli:divide><xbrli:unitNumerator><xbrli:measure>iso4217:INR</xbrli:measure></xbrli:unitNumerator><xbrli:unitDenominator><xbrli:measure>xbrli:shares</xbrli:measure></xbrli:unitDenominator></xbrli:divide></xbrli:unit>';if(u==='pure')return'<xbrli:unit id="pure"><xbrli:measure>xbrli:pure</xbrli:measure></xbrli:unit>';return''}
function decimals(v){const s=String(v).trim();if(!s)return'0';if(!/^-?\d+(?:\.\d+)?$/.test(s))return'0';const i=s.indexOf('.');return i<0?'0':String(s.length-i-1)}
function xmlEscape(s){return esc(s).replace(/&#39;/g,"&apos;")}
function htmlSafe(raw){if(!raw)return'';const bad=[];const allowed=new Set(['div','span','p','br','table','td','tr','thead','tfoot','tbody','th','col','colgroup']);const d=new DOMParser().parseFromString(`<div>${raw}</div>`,'text/html');d.querySelectorAll('*').forEach(n=>{if(!allowed.has(n.tagName.toLowerCase()))bad.push(n.tagName.toLowerCase());for(const a of n.attributes)if(a.name.toLowerCase()==='style')bad.push('style attribute');});if(bad.length)throw new Error('MCA HTML violation: '+[...new Set(bad)].join(', '));return d.body.firstElementChild.innerHTML}
function contextsForXml(){const cs=buildContexts();const map=new Map(cs.map(c=>[c.sig,c]));const get=(period,dims)=>map.get(JSON.stringify([period,period==='current'?currentDates():priorDates(),dims]));return {cs,map,get}}
function factsForXml(){const arr=[];for(const [k,v] of Object.entries(state.facts)){if(!nonblank(v))continue;const [concept,period]=k.split('|');arr.push({concept,period,value:v,dims:[]})}for(const [role,rows] of Object.entries(state.dimRows))for(const row of rows){if(!nonblank(row.line))continue;const dims=Object.entries(row.dims||{}).filter(x=>nonblank(x[1])).map(([axis,member])=>({axis,member}));for(const period of ['current','prior'])if(nonblank(row[period]))arr.push({concept:row.line,period,value:row[period],dims})}return arr}
function generateXML(){
const p=state.profile;if(!p.cin||!p.companyName||!p.fyStart||!p.fyEnd)return{error:'Complete CIN, company name, FY start and FY end first.'};
const pre=runChecks();const blocking=pre.filter(i=>i.level==='error');if(blocking.length)return{error:`XML generation blocked: ${blocking.length} preflight error(s) remain. Open Rules & preflight to resolve them.`};
autoCalculate();const {cs,get}=contextsForXml();const facts=factsForXml();const used=new Set(),units=new Set();
for(const f of facts){const c=get(f.period,f.dims);if(c)used.add(c.id);const u=unitFor(el(f.concept));if(u)units.add(u)}
let x=`<?xml version="1.0" encoding="UTF-8"?>\n<xbrli:xbrl xmlns:xbrli="http://www.xbrl.org/2003/instance" xmlns:link="http://www.xbrl.org/2003/linkbase" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xbrldi="http://xbrl.org/2006/xbrldi" xmlns:ind-as="http://www.icai.org/xbrl/taxonomy/2017-03-31/ind-as" xmlns:in-ca="http://www.icai.org/xbrl/taxonomy/2017-03-31/in-ca" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">\n  <link:schemaRef xlink:type="simple" xlink:href="${DATA.meta.schemaRef}"/>\n`;
for(const c of cs)if(used.has(c.id)){x+=`  <xbrli:context id="${c.id}"><xbrli:entity><xbrli:identifier scheme="${DATA.meta.entityScheme}">${xmlEscape(p.cin)}</xbrli:identifier></xbrli:entity><xbrli:period>`;if(c.instant)x+=`<xbrli:instant>${c.instant}</xbrli:instant>`;else x+=`<xbrli:startDate>${c.start}</xbrli:startDate><xbrli:endDate>${c.end}</xbrli:endDate>`;x+=`</xbrli:period>`;if(c.dims.length){x+='<xbrli:scenario>';for(const d of c.dims){const ae=el(d.axis);if(ae?.typedDomainRef){const dom=idToQName(ae.typedDomainRef);x+=`<xbrldi:typedMember dimension="${xmlEscape(d.axis)}"><${dom}>${xmlEscape(d.member)}</${dom}></xbrldi:typedMember>`}else x+=`<xbrldi:explicitMember dimension="${xmlEscape(d.axis)}">${xmlEscape(d.member)}</xbrldi:explicitMember>`}x+='</xbrli:scenario>'}x+='</xbrli:context>\n'}
for(const u of units){const fake={type:u==='INR'?'xbrli:monetaryItemType':u==='shares'?'xbrli:sharesItemType':u==='INRPerShare'?'num:perShareItemType':'xbrli:decimalItemType'};x+='  '+unitXML(fake)+'\n'}
const seen=new Set(), factIds=new Map();
for(const f of facts){const e=el(f.concept);if(!e)continue;const c=get(f.period,f.dims);if(!c)continue;const key=f.concept+'|'+c.id;if(seen.has(key))continue;seen.add(key);const pref=f.concept.split(':')[0],local=f.concept.split(':')[1],fid='f'+Math.abs(hashCode(key));factIds.set(f.concept+'|'+f.period+'|'+JSON.stringify(f.dims),fid);const attrs=` id="${fid}" contextRef="${c.id}"${unitFor(e)?` unitRef="${unitFor(e)}" decimals="${decimals(f.value)}"`:''}${typeKind(e)==='html'?' xml:lang="en"':''}`;
if(typeKind(e)==='html'){let h;try{h=htmlSafe(f.value)}catch(err){return{error:err.message}}x+=`  <${pref}:${local}${attrs}>${h}</${pref}:${local}>\n`}else x+=`  <${pref}:${local}${attrs}>${xmlEscape(f.value)}</${pref}:${local}>\n`}
const footLinks=[];
for(const f of state.footnotes||[]){if(!nonblank(f.text)||!nonblank(f.fact))continue;const [concept,period]=f.fact.split('|');const fid=factIds.get(concept+'|'+period+'|[]');if(!fid)continue;const lab='fn_'+footLinks.length;footLinks.push({fid,lab,text:f.text})}
if(footLinks.length){x+='  <link:footnoteLink xlink:type="extended">\n';footLinks.forEach((f,i)=>{x+=`    <link:loc xlink:type="locator" xlink:label="${f.lab}" xlink:href="#${f.fid}"/>\n`;x+=`    <link:footnote xlink:type="resource" xlink:label="${f.lab}_r" xml:lang="en">${htmlSafe(f.text)}</link:footnote>\n`;x+=`    <link:footnoteArc xlink:type="arc" xlink:arcrole="http://www.xbrl.org/2003/arcrole/fact-footnote" xlink:from="${f.lab}" xlink:to="${f.lab}_r"/>\n`});x+='  </link:footnoteLink>\n'}
x+='</xbrli:xbrl>';return{xml:x}}
function autoCalculate(){
  const byRole={};
  for(const a of (DATA.calculations||[]))(byRole[a.role]??=[]).push(a);
  for(const period of ['current','prior']){
    let changed=true,guard=0;
    while(changed&&guard++<5){
      changed=false;
      for(const role of Object.keys(byRole)){
        const arcs=byRole[role];
        const parents=new Set(arcs.map(a=>a.from));
        for(const parent of parents){
          const e=el(parent);
          if(!e||typeKind(e)==='text'||typeKind(e)==='html')continue;
          const children=arcs.filter(a=>a.from===parent);
          let sum=0,has=false;
          for(const a of children){
            const v=Number(state.facts[a.to+'|'+period]);
            if(Number.isFinite(v)){sum+=v*Number(a.weight||1);has=true}
          }
          if(has&&!nonblank(state.facts[parent+'|'+period])){
            state.facts[parent+'|'+period]=String(Math.round((sum+Number.EPSILON)*100)/100);
            changed=true;
          }
        }
      }
    }
  }
}
function idToQName(id){const e=DATA.elements.find(x=>x.id===id);return e?e.q:id}
function hashCode(s){let h=0;for(let i=0;i<s.length;i++)h=((h<<5)-h)+s.charCodeAt(i)|0;return h}
function calcPage(){
const rows=(DATA.calculations||[]).map(a=>{const pv=Number(state.facts[a.from+'|current']),cv=Number(state.facts[a.to+'|current']);const populated=Number.isFinite(pv)||Number.isFinite(cv);const expected=Number.isFinite(cv)?cv*Number(a.weight||1):null;const ok=!Number.isFinite(pv)||!Number.isFinite(expected)||Math.abs(pv-expected)<=0.01;return {...a,pv,cv,expected,populated,ok}});
const shown=rows.filter(r=>!state.showOnlyPopulated||r.populated);
return `<div class="card"><div class="toolbar"><div class="grow"><h2>Calculation relationships</h2><div class="hint">${rows.length} taxonomy calculation arcs. Populated relationships are checked using the MCA calculation linkbase weight.</div></div><label class="hint"><input id="calcPopulatedOnly" type="checkbox" ${state.showOnlyPopulated?'checked':''}> populated only</label></div><div class="table-wrap"><table class="table"><thead><tr><th>Parent</th><th>Child</th><th>Weight</th><th>Current parent</th><th>Expected</th><th>Status</th></tr></thead><tbody>${shown.slice(0,1200).map(r=>`<tr><td><b>${esc(el(r.from)?.label||r.from)}</b><div class="code">${esc(r.from)}</div></td><td>${esc(el(r.to)?.label||r.to)}<div class="code">${esc(r.to)}</div></td><td>${esc(r.weight)}</td><td>${Number.isFinite(r.pv)?r.pv:''}</td><td>${Number.isFinite(r.expected)?r.expected.toFixed(2):''}</td><td>${!r.populated?'<span class="status">Not populated</span>':r.ok?'<span class="status">Consistent</span>':'<span class="req">INCONSISTENT</span>'}</td></tr>`).join('')||'<tr><td colspan=6 class="empty">No calculation relationships match the filter.</td></tr>'}</tbody></table></div><p class="hint">Only the first 1,200 rows are rendered for browser performance; the preflight engine evaluates the complete calculation set.</p></div>
<div class="card" style="margin-top:14px"><h2>Opening / closing continuity</h2><p class="hint">The supplied MCA formula groups are checked for prior closing = current opening and opening + change = current closing.</p>${(DATA.openingClosing||[]).slice(0,80).map(g=>{const [o,ch,c]=g;const pv=Number(state.facts[c+'|prior']),ov=Number(state.facts[o+'|current']),cv=Number(state.facts[ch+'|current']),cl=Number(state.facts[c+'|current']);const populated=[pv,ov,cv,cl].some(Number.isFinite);const ok=(!Number.isFinite(pv)||!Number.isFinite(ov)||Math.abs(pv-ov)<=.01)&&(!Number.isFinite(ov)||!Number.isFinite(cv)||!Number.isFinite(cl)||Math.abs(ov+cv-cl)<=.01);return `<div class="issue"><b>${esc(el(o)?.label||o)}</b> → ${esc(el(ch)?.label||ch)} → ${esc(el(c)?.label||c)} <span class="code">${populated?(ok?'consistent':'check values'):'not populated'}</span></div>`}).join('')}</div>`
}
function xmlView(){const r=generateXML();if(r.error)return `<div class="card"><h2>XML cannot yet be generated</h2><div class="issue err">${esc(r.error)}</div></div>`;return `<div class="card"><div class="toolbar"><div class="grow"><h2>Generated instance</h2><div class="hint">V4 blocks XML generation while local preflight has errors. After generation, still load the XML into the MCA XBRL Validation Tool and perform validation/pre-scrutiny.</div></div><button class="smallbtn primary" data-downloadxml>Download XML</button></div><textarea style="width:100%;min-height:600px;font:12px ui-monospace,monospace;border:1px solid var(--line);border-radius:8px;padding:10px">${esc(r.xml)}</textarea></div>`}
function rules(){const issues=runChecks();const q=state.ruleQuery.toLowerCase();const generic=DATA.genericRules.filter(r=>!q||String(r.rule).toLowerCase().includes(q)||String(r.no).toLowerCase().includes(q));const specific=DATA.specificRules.filter(r=>!q||String(r.rule).toLowerCase().includes(q)||String(r.q).toLowerCase().includes(q)||String(r.name||'').toLowerCase().includes(q));const metrics=RULES?.stats||{total:0,conditional:0,unconditionalMandatory:0,constraints:0,relations:0,unknown:0};return `<div class="grid three"><div class="card"><h2>Preflight result</h2><div class="progress"><i style="width:${issues.length?Math.max(5,100-Math.min(95,issues.filter(x=>x.level==='error').length*8)):100}%"></i></div><p>${issues.length?`<b>${issues.filter(x=>x.level==='error').length}</b> errors and <b>${issues.filter(x=>x.level==='warning').length}</b> warnings`:'No preflight findings.'}</p><button class="smallbtn primary" data-runchecks>Run again</button><button class="smallbtn" data-go="xml" style="margin-left:6px">Open XML gate</button></div><div class="card"><h2>V4 parser coverage</h2><p><b>${metrics.total}</b> specific rules parsed</p><p class="hint">${metrics.conditional} conditional • ${metrics.unconditionalMandatory} unconditional mandatory • ${metrics.constraints} constraint-bearing • ${metrics.relations} relationship-bearing</p></div><div class="card"><h2>Rule library</h2><p class="hint">Structured execution now separates applicability conditions, target constraints and cross-concept relationships. ${DATA.genericRules.length} generic rules and ${DATA.specificRules.length} specific rows are retained.</p><input class="search" id="ruleSearch" value="${esc(state.ruleQuery)}" placeholder="Search rule text or concept…"></div></div><div class="card" style="margin-top:14px"><h2>Findings</h2>${issues.map(i=>`<div class="issue ${i.level==='error'?'err':i.level==='warning'?'warn':''}"><b>${esc(i.level.toUpperCase())}</b> — ${esc(i.message)}${i.concept?` <span class="code">${esc(i.concept)}</span>`:''}${i.ruleId?` <span class="code">${esc(i.ruleId)}</span>`:''}</div>`).join('')||'<div class="empty">No findings.</div>'}</div><div class="card" style="margin-top:14px"><h2>Matching MCA rules</h2><div class="hint">${generic.length+specific.length} matching rules${metrics.unknown?` • ${metrics.unknown} specific rows remain advisory-only because their text could not be safely converted into a deterministic predicate`:''}</div>${generic.map(r=>`<details><summary>Generic rule ${esc(r.no)}</summary><p>${esc(r.rule)}</p></details>`).join('')}${specific.slice(0,500).map(r=>{const d=RULES?.rules?.find(x=>x.q===r.q&&x.text===r.rule);return `<details><summary>${esc(r.q)} — ${esc(r.name||'specific rule')} ${d?'<span class="status">parsed</span>':'<span class="status">advisory</span>'}</summary><p>${esc(r.rule)}</p></details>`}).join('')}</div>`}
let RULES=null;
function runSpecificBusinessRules(add){
  if(!RULES) RULES=window.IndAsRuleEngine.compile(DATA);
  state.ruleFindings=window.IndAsRuleEngine.evaluate(RULES,DATA,state);
  for(const f of state.ruleFindings) add(f.level,f.message,f.concept,{ruleId:f.ruleId,ruleText:f.ruleText,details:f.details});
}
function runGenericRuleChecks(add){
  if(!window.IndAsRuleEngine)return;
  const rows=window.IndAsRuleEngine.evaluateGeneric(DATA,state);
  for(const f of rows) add(f.level,f.message,f.concept,{ruleId:f.ruleId,ruleText:f.ruleText,details:f.details});
}
function runNotAllChecks(add){
  if(!window.IndAsRuleEngine)return;
  window.IndAsRuleEngine.evaluateNotAll(DATA,state,(level,message,concept,meta)=>add(level,message,concept,meta));
}
function isCurrencyException(c){const n=c.split(':')[1];return ['ShareCapitalOfSubsidiary','ReservesAndSurplusOfSubsidiary','TotalAssetsOfSubsidiary','TotalLiabilitiesOfSubsidiary','InvestmentOfSubsidiary','TurnoverOfSubsidiary','ProfitBeforeTaxOfSubsidiary','ProvisionForTaxOfSubsidiary','ProfitAfterTaxOfSubsidiary','ProposedDividendOfSubsidiary','NoncontrollingInterestsOfSubsidiary','CurrentAssetsOfSubsidiary','NoncurrentAssetsOfSubsidiary','CurrentLiabilitiesOfSubsidiary','NoncurrentLiabilitiesOfSubsidiary','RevenueOfSubsidiary','ComprehensiveIncomeOfSubsidiary','ProfitLossAttributableToNoncontrollingInterests','DividendsPaidToNoncontrollingInterests'].includes(n)}
function dateException(c){return /Subsidiary|PartnershipFirm|DateToWhichCapitalOfPartnership|DateOfBirthOfKeyManagerialPersonnelOrDirector/.test(c)}
function filterConcepts(q=''){const needle=q.toLowerCase();$$('#factBody tr').forEach(r=>{const key=r.dataset.search||'';const concept=r.querySelector('.code')?.textContent||'';const populated=[...r.querySelectorAll('.fact-input')].some(x=>nonblank(x.value));r.hidden=(needle&&!key.includes(needle))||(state.showOnlyPopulated&&!populated)})}
function saveProfile(){ $$('[data-profile]').forEach(x=>{let v=x.value;if(x.dataset.profile==='firstYear')v=x.value==='true';state.profile[x.dataset.profile]=v});dirty();render()}
function bind(){setFactInputs();$$('[data-profile]').forEach(x=>x.onchange=saveProfile);$$('[data-go]').forEach(x=>x.onclick=()=>{state.page=x.dataset.go;render()});$$('[data-dimrole]').forEach(x=>x.onclick=()=>{state.page='dimensions';state.__role=x.dataset.dimrole;render()});$$('[data-runchecks]').forEach(x=>x.onclick=()=>render());$('#conceptSearch')?.addEventListener('input',e=>filterConcepts(e.target.value));$('#populatedOnly')?.addEventListener('change',e=>{state.showOnlyPopulated=e.target.checked;filterConcepts($('#conceptSearch')?.value||'')});$('#ruleSearch')?.addEventListener('input',e=>{state.ruleQuery=e.target.value;render()});$('#calcPopulatedOnly')?.addEventListener('change',e=>{state.showOnlyPopulated=e.target.checked;render()});$$('[data-addrow]').forEach(x=>x.onclick=()=>{const role=x.dataset.addrow;(state.dimRows[role]??=[]).push({_role:role,_i:(state.dimRows[role]||[]).length,line:'',dims:{},current:'',prior:''});dirty();render()});$$('[data-delrow]').forEach(x=>x.onclick=()=>{state.dimRows[x.dataset.delrow].splice(+x.dataset.i,1);dirty();render()});$$('[data-dr]').forEach(x=>x.onchange=()=>{const r=state.dimRows[x.dataset.dr][+x.dataset.i];if(x.dataset.k==='line')r.line=x.value;else if(x.dataset.period)r[x.dataset.period]=x.value;else r.dims[x.dataset.axis]=x.value;dirty()});$$('[data-dimback]').forEach(x=>x.onclick=()=>{state.page='dimensions';state.__role=null;render()});$$('[data-addfoot]').forEach(x=>x.onclick=()=>{state.footnotes.push({fact:'',text:''});dirty();render()});$$('[data-foot]').forEach(x=>x.onchange=()=>{state.footnotes[+x.dataset.foot][x.dataset.k]=x.value;dirty()});$$('[data-downloadxml]').forEach(x=>x.onclick=downloadXML)}
function downloadXML(){const r=generateXML();if(r.error){toast(r.error);return}const blob=new Blob([r.xml],{type:'application/xml;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${state.profile.cin||'IND-AS'}_${state.profile.fyEnd||'filing'}.xml`;a.click();URL.revokeObjectURL(a.href)}
function render(){nav();header();tabs();let html='';if(state.page==='home')html=home();else if(state.page==='general')html=general();else if(state.page==='sections')html=sections();else if(state.page==='dimensions')html=state.__role?dimEditor(state.__role):dimensions();else if(state.page==='contexts')html=contexts();else if(state.page==='rules')html=rules();else if(state.page==='calc')html=calcPage();else if(state.page==='xml')html=xmlView();$('#content').innerHTML=html;$('#errCount').textContent=state.issues.filter(x=>x.level==='error').length;$('#warnCount').textContent=state.issues.filter(x=>x.level==='warning').length;bind();if(state.dirty)$('#saveState').textContent='Changed'}
function loadSaved(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');if(x){Object.assign(state,x);toast('Restored your last local project.')}}catch{}}
async function loadData(){for(const u of DATA_URLS){try{const r=await fetch(u);if(r.ok)return await r.json()}catch{}} for(const set of COMPRESSED_DATA_SETS){try{const rs=await Promise.all(set.map(u=>fetch(u)));if(rs.some(r=>!r.ok))continue;const b64=(await Promise.all(rs.map(r=>r.text()))).join('');const bin=Uint8Array.from(atob(b64),c=>c.charCodeAt(0));if('DecompressionStream' in window){const ds=new DecompressionStream('gzip');const txt=await new Response(new Blob([bin]).stream().pipeThrough(ds)).text();return JSON.parse(txt.replace(/\bNaN\b/g,'null'))}}catch{}} throw Error('Taxonomy data is unavailable in this browser.')}
async function init(){DATA=await loadData();DATA._emap=Object.fromEntries(DATA.elements.map(e=>[e.q,e]));RULES=window.IndAsRuleEngine.compile(DATA);loadSaved();state.issues=runChecks();render();window.setInterval(()=>{state.issues=runChecks();$('#errCount').textContent=state.issues.filter(x=>x.level==='error').length;$('#warnCount').textContent=state.issues.filter(x=>x.level==='warning').length},2000)}
$$('[data-action="save"]').forEach(b=>b.onclick=save);$$('[data-action="xml"]').forEach(b=>b.onclick=()=>{state.issues=runChecks();state.page='xml';render()});$$('[data-action="new"]').forEach(b=>b.onclick=()=>{if(confirm('Start a new filing? Unsaved browser data will be replaced.')){localStorage.removeItem(KEY);location.reload()}});$$('[data-action="restore"]').forEach(b=>b.onclick=()=>{loadSaved();render()});$$('[data-action="import"]').forEach(b=>b.onclick=()=>$('#fileImport').click());
$('#fileImport').onchange=async e=>{const f=e.target.files[0];if(!f)return;const text=await f.text();if(f.name.endsWith('.json')){try{const x=JSON.parse(text);Object.assign(state,x);dirty();render();toast('Project JSON imported.')}catch{toast('Invalid project JSON.')}return}try{importXML(text);toast('XBRL imported into the filing workspace.');render()}catch(err){toast('Import failed: '+err.message)}};
function importXML(text){const doc=new DOMParser().parseFromString(text,'application/xml');if(doc.querySelector('parsererror'))throw Error('XML parser error');const root=doc.documentElement;const ctxs={};root.querySelectorAll('context').forEach(c=>{const id=c.getAttribute('id'),i=c.querySelector('instant'),s=c.querySelector('startDate'),en=c.querySelector('endDate');ctxs[id]={instant:i?.textContent||'',start:s?.textContent||'',end:en?.textContent||'',dims:[...c.querySelectorAll('explicitMember')].map(m=>({axis:m.getAttribute('dimension'),member:m.textContent}))}});const prefixNS={'http://www.icai.org/xbrl/taxonomy/2017-03-31/ind-as':'ind-as','http://www.icai.org/xbrl/taxonomy/2017-03-31/in-ca':'in-ca'};root.querySelectorAll('[contextRef]').forEach(f=>{const nsuri=f.namespaceURI,pref=prefixNS[nsuri],local=f.localName;if(!pref)return;const c=ctxs[f.getAttribute('contextRef')];const qn=pref+':'+local;const period=c?.end===state.profile.fyEnd?'current':'prior';const dims=c?.dims||[];if(dims.length){let role=DATA.elrs.find(r=>r.lineItems.some(x=>x.q===qn)&&dims.every(d=>r.axes.some(a=>a.q===d.axis&&(a.typed||a.members.some(m=>m.q===d.member)))) )?.role;if(role){const rows=state.dimRows[role]??=[];let row=rows.find(r=>r.line===qn&&JSON.stringify(r.dims)===JSON.stringify(Object.fromEntries(dims.map(d=>[d.axis,d.member]))));if(!row){row={_role:role,line:qn,dims:Object.fromEntries(dims.map(d=>[d.axis,d.member])),current:'',prior:''};rows.push(row)}row[period]=f.textContent}}else state.facts[qn+'|'+period]=f.textContent})}
init();